import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { assert, describe, it } from "vite-plus/test";

const captureSource = readFileSync(
  resolve(import.meta.dirname, "capture-shared-workbench.mjs"),
  "utf8",
);
const readerSource = readFileSync(
  resolve(import.meta.dirname, "shared-workbench/workbench.js"),
  "utf8",
);
const appEntrySource = readFileSync(resolve(import.meta.dirname, "../src/app/index.tsx"), "utf8");
const isolatedEntrySource = readFileSync(
  resolve(import.meta.dirname, "../src/app/components-lab-isolated.tsx"),
  "utf8",
);

describe("Components Lab paired workbench", () => {
  it("reads the same shared story contract from both renderers", () => {
    assert.include(readerSource, "function readComponentLabMetrics(root)");
    assert.include(readerSource, '[data-component-lab="web-lynx-shared"]');
    assert.include(readerSource, "data-component-states");
    assert.include(readerSource, 'story.querySelectorAll("[data-slot]")');
    assert.include(captureSource, "const componentLabReady =");
    assert.include(captureSource, "const componentLabGeometryReady =");
    assert.include(captureSource, "const componentLabTooltipReady =");
    assert.include(captureSource, '"component-lab-tooltip", "hover"');
    assert.include(captureSource, "const componentLabMenuReady =");
    assert.include(captureSource, 'invokeLynxMenu?.("component-lab-menu")');
    assert.include(captureSource, "state.web.componentLabMetrics.menu.items.length === 2");
    assert.include(readerSource, '[data-floating-popup="component-lab-menu"]');
    assert.include(readerSource, "separatorCount");
    assert.include(readerSource, "shortcutCount");
    assert.include(captureSource, "componentLabMenuEvidence");
    assert.include(readerSource, 'story.querySelectorAll("[data-slot]")');
    assert.include(captureSource, "const componentLabSelectReady =");
    assert.include(captureSource, '"Density Comfortable Compact"');
    assert.include(captureSource, 'select?.value === "Compact"');
    assert.include(captureSource, '[data-component-lab-select-item="compact"]');
    assert.include(captureSource, "componentLabSelectEvidence.web.popup.box.rect.x -");
    assert.include(captureSource, "componentLabSelectEvidence.web.trigger.rect.x");
    assert.include(readerSource, '[data-floating-popup="component-lab-select"]');
    assert.include(readerSource, "groupCount");
    assert.include(readerSource, "labelCount");
    assert.include(captureSource, "const componentLabNumberReady =");
    assert.include(captureSource, '[data-component-lab-number-action="increment"]');
    assert.include(captureSource, '[data-component-lab-number-action="decrement"]');
    assert.include(readerSource, '[data-component-lab-number-input="value"]');
    assert.include(captureSource, "const componentLabScrollReady =");
    assert.include(captureSource, '".component-lab-scroll-area"');
    assert.include(captureSource, "dispatchMouseWheel");
    assert.include(readerSource, "scrollArea: (() =>");
    assert.include(readerSource, "scrollHeight");
    assert.include(captureSource, "const componentLabDialogReady =");
    assert.include(captureSource, '[data-component-lab-dialog-trigger=\"default\"]');
    assert.include(captureSource, '[data-component-lab-dialog-close=\"default\"]');
    assert.include(readerSource, '[data-component-lab-dialog-popup="default"]');
    assert.include(readerSource, "backdropCount");
    assert.include(readerSource, "viewportCount");
    assert.include(captureSource, "componentLabDialogEvidence");
    assert.include(captureSource, "const componentLabSheetReady =");
    assert.include(captureSource, '[data-component-lab-sheet-trigger=\"default\"]');
    assert.include(captureSource, '[data-component-lab-sheet-close=\"default\"]');
    assert.include(readerSource, '[data-component-lab-sheet-popup="default"]');
    assert.include(readerSource, '[data-slot="sheet-header"]');
    assert.include(readerSource, '[data-slot="sheet-panel"]');
    assert.include(readerSource, '[data-slot="sheet-footer"]');
    assert.include(readerSource, '[data-slot="sheet-title"]');
    assert.include(readerSource, '[data-slot="sheet-description"]');
    assert.include(readerSource, "sheetViewportCount");
    assert.include(readerSource, "sheetBackdropCount");
    assert.include(captureSource, "componentLabMetrics?.sheetViewportCount === 0");
    assert.include(captureSource, "componentLabMetrics?.sheetBackdropCount === 0");
    assert.include(captureSource, "sheet.popup.style?.opacity");
    assert.include(captureSource, 'inputChannel: "sequential-dual-cdp-pointer"');
    assert.include(captureSource, "const componentLabPopoverReady =");
    assert.include(captureSource, '[data-component-lab-popover-trigger=\"default\"]');
    assert.include(captureSource, '[data-component-lab-popover-close=\"default\"]');
    assert.include(readerSource, '[data-component-lab-popover-popup="default"]');
    assert.include(captureSource, "const componentLabProjectFaviconReady =");
    assert.include(readerSource, "projectFavicon: (() =>");
    assert.include(readerSource, '".component-lab-project-favicon"');
    assert.include(captureSource, "const componentLabSettingResetReady =");
    assert.include(captureSource, '[aria-label=\"Reset appearance to default\"]');
    assert.include(readerSource, "settingReset: (() =>");
    assert.include(captureSource, "const componentLabSidebarReady =");
    assert.include(captureSource, '[data-component-lab-sidebar-menu-button=\"default\"]');
    assert.include(readerSource, "sidebarPrimitive: (() =>");
    assert.include(readerSource, '".component-lab-sidebar-inset"');
    assert.include(captureSource, "sidebarPrimitive?.inset?.rect?.width === 216");
    assert.include(readerSource, "command: (() =>");
    assert.include(readerSource, '[data-slot="command-item"]');
    assert.include(readerSource, '[data-slot="command-panel"]');
    assert.include(readerSource, '[data-slot="command-footer"]');
    assert.include(readerSource, "separatorCount");
    assert.include(readerSource, "shortcutText");
    assert.include(readerSource, '[data-slot="command-empty"]');
    assert.include(captureSource, "const componentLabCommandReady =");
    assert.include(captureSource, 'JSON.stringify(["Open project ⌘O", "New thread"])');
    assert.include(captureSource, "Could not focus Web component lab CommandInput");
    assert.include(captureSource, "Could not focus Lynx component lab CommandInput");
    assert.include(captureSource, "componentLabCommandEvidence");
    assert.include(captureSource, "Could not clear Web component lab CommandInput");
    assert.include(captureSource, "Could not clear Lynx component lab CommandInput");
    assert.include(captureSource, '"No matching commands."');
    assert.include(captureSource, "const componentLabCommandDialogReady =");
    assert.include(readerSource, '[data-component-lab-command-dialog-trigger="default"]');
    assert.include(captureSource, '[data-component-lab-command-dialog-open="default"]');
    assert.include(captureSource, '[data-component-lab-command-dialog-close="default"]');
    assert.include(readerSource, '[data-component-lab-command-dialog-popup="default"]');
    assert.include(captureSource, "componentLabSelectEvidence");
    assert.include(captureSource, "componentLabSelectClosedAfterEvidence");
    assert.include(readerSource, "baseUiInertCount");
    assert.include(readerSource, "threadErrorBanner: (() =>");
    assert.include(captureSource, "componentLabThreadErrorEvidence");
    assert.include(readerSource, "threadStatusLabels:");
    assert.include(captureSource, "const componentLabThreadStatusReady =");
    assert.include(readerSource, "changeRequests:");
    assert.include(captureSource, "const componentLabChangeRequestReady =");
    assert.include(readerSource, "worktreeIndicator: (() =>");
    assert.include(captureSource, "const componentLabWorktreeReady =");
    assert.include(readerSource, "sidebarChrome: (() =>");
    assert.include(captureSource, "const componentLabSidebarChromeReady =");
    assert.include(readerSource, "fileTree: (() =>");
    assert.include(captureSource, "const componentLabFileTreeReady =");
    assert.include(readerSource, "changedFilesCard: (() =>");
    assert.include(captureSource, "const componentLabChangedFilesCardReady =");
    assert.include(readerSource, "chatHeader: (() =>");
    assert.include(captureSource, "const componentLabChatHeaderReady =");
    assert.include(readerSource, "plan: (() =>");
    assert.include(captureSource, "const componentLabPlanReady =");
    assert.include(captureSource, 'lynxHovered === "true"');
    assert.include(readerSource, "hostList: (() =>");
    assert.include(captureSource, "const componentLabHostListReady =");
    assert.include(readerSource, "hostLayout: (() =>");
    assert.include(captureSource, "const componentLabHostLayoutReady =");
    assert.include(readerSource, "t3Wordmarks:");
    assert.include(captureSource, "const componentLabT3WordmarkReady =");
    assert.include(readerSource, "updatePills:");
    assert.include(captureSource, "const componentLabUpdatePillReady =");
    assert.include(captureSource, "const componentLabDraftInputReady =");
    assert.include(captureSource, "Could not focus Web component lab DraftInput");
    assert.include(captureSource, "Could not focus Lynx component lab DraftInput");
    assert.include(readerSource, "draftInput: (() =>");
    assert.include(captureSource, "const componentLabLabelReady =");
    assert.include(readerSource, '[data-component-lab-label="project-name"]');
    assert.include(captureSource, "componentLabSidebarToggled");
    assert.include(captureSource, '"collapsed"');
    assert.include(captureSource, 'semanticRoute === "components-lab"');
    assert.include(captureSource, '? "/components-lab"');
    assert.include(captureSource, "componentLabCatalog.length");
    assert.include(captureSource, 'argValue("--component-story", "")');
    assert.include(captureSource, "expectedComponentLabStoryCount");
    assert.include(captureSource, "isolatedComponentStoryReady");
    assert.include(captureSource, "CommandPaletteSurface#PaletteSectionSurface");
    assert.include(captureSource, "settings/SettingsSurfaces#SourceControlMarkSurface");
    assert.include(readerSource, "paletteSection: (() =>");
    assert.include(readerSource, "sourceControlMarks:");
    assert.include(readerSource, 'url.searchParams.get("componentStory")');
    assert.include(readerSource, 'lynxQuery.set("componentStory", componentStory)');
    assert.include(captureSource, "components-lab-isolated.web.bundle");
    assert.notInclude(appEntrySource, "ComponentLabIsolatedSurface");
    assert.include(isolatedEntrySource, "ComponentLabIsolatedSurface");
    assert.include(readerSource, "expectedComponentStoryCount");
    assert.include(captureSource, "const pass = isComponentsLabState");
    assert.include(readerSource, 'expectedSemanticRoute === "components-lab"');
    assert.include(captureSource, "isComponentsLabState &&");
    assert.include(captureSource, "HTTP Authentication failed; no valid credentials available");
  });
});
